-- SEED INITIAL COURSES
INSERT INTO public.courses (id, title, description, difficulty, total_prompts, icon_name, color, created_at)
VALUES 
('course-1', 'AI Literacy 101', 'Learn the fundamentals of communicating effectively with AI. Perfect for complete beginners who want to understand how to ask questions and get useful responses.', 'beginner', 25, 'GraduationCap', '#3b82f6', NOW()),
('course-2', 'Prompt Engineering Basics', 'Take your AI skills to the next level. Learn techniques like chain-of-thought prompting, role assignment, and how to get more precise outputs.', 'intermediate', 20, 'Zap', '#8b5cf6', NOW()),
('course-3', 'AI for Business Professionals', 'Practical AI applications for the workplace. From email drafting to data analysis, learn to use AI as your productivity partner.', 'beginner', 30, 'Briefcase', '#10b981', NOW()),
('course-4', 'Code with AI', 'Master the art of coding with AI assistance. Learn debugging strategies, code review techniques, and architectural discussions.', 'intermediate', 35, 'Code', '#f59e0b', NOW()),
('course-5', 'Advanced Prompt Engineering', 'For power users ready to master complex prompting techniques. Includes few-shot learning, structured outputs, and multi-step reasoning.', 'advanced', 40, 'Rocket', '#ef4444', NOW()),
('course-chatgpt', 'ChatGPT Mastery', 'Unlock the full potential of ChatGPT. Master GPT-4o, Custom GPTs, and advanced data analysis.', 'beginner', 20, 'Sparkles', '#10a37f', NOW()),
('course-perplexity', 'Perplexity Deep Research', 'Learn to use Perplexity AI as your ultimate research assistant and search engine replacement.', 'beginner', 15, 'Search', '#00aeef', NOW()),
('course-claude', 'Claude for Creative & Tech', 'Master Claude 3.5 Sonnet for superior coding, long-document analysis, and creative writing.', 'intermediate', 25, 'Zap', '#d97706', NOW()),
('course-kimi', 'Kimi for Long Context', 'Specialized techniques for Kimi AI, focusing on massive document processing and long-context reasoning.', 'intermediate', 20, 'BookOpen', '#3b82f6', NOW()),
('course-deepseek', 'DeepSeek Coding Power', 'Master DeepSeek Coder and V3 for efficient programming and high-performance logic generation.', 'advanced', 30, 'Code', '#6366f1', NOW()),
('course-gemini', 'Gemini Multimodal Expert', 'Leverage Google Gemini for multimodal tasks across text, image, and code with massive context windows.', 'intermediate', 25, 'Rocket', '#4285f4', NOW())
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  total_prompts = EXCLUDED.total_prompts,
  icon_name = EXCLUDED.icon_name,
  color = EXCLUDED.color;
-- SEED INITIAL PROMPTS (AI Literacy 101)
INSERT INTO public.course_prompts (id, course_id, module_name, prompt_order, prompt_text, learning_goal, estimated_time_minutes, tips, resources, created_at)
VALUES 
('prompt-1-1', 'course-1', 'Module 1: Person - Understanding AI & Your Role', 1, 'Explain to me what a Large Language Model (LLM) is in simple terms. Use an analogy that a 12-year-old could understand.', 'Understand the basic concept of what AI language models are and how they work', 10, '{ "Ask follow-up questions if the analogy doesn''t make sense", "Try asking \"Why can''t AI actually think like humans?\"", "Request a simpler explanation if needed" }', '[{"title": "What is ChatGPT?", "url": "https://openai.com/chatgpt"}]', NOW()),
('prompt-1-2', 'course-1', 'Module 1: Person - Understanding AI & Your Role', 2, 'I''m a [your job title or student]. Help me identify 3 specific tasks in my daily routine where AI could save me time or help me work better.', 'Identify personal AI use cases relevant to your life', 10, '{ "Be specific about what you actually do day-to-day", "Ask the AI to prioritize by time-saving potential", "Request step-by-step guidance for implementing the suggestions" }', '[]', NOW()),
('prompt-1-3', 'course-1', 'Module 1: Person - Understanding AI & Your Role', 3, 'What are 5 things you CANNOT do as an AI? I want to understand your limitations so I know what tasks are better suited for humans.', 'Understand AI limitations to set appropriate expectations', 8, '{ "Take note of the specific limitations mentioned", "Ask for examples of tasks that require human judgment", "Consider how this affects your earlier use case ideas" }', '[]', NOW()),
('prompt-2-1', 'course-1', 'Module 2: Problem - Common AI Challenges', 4, 'Tell me about "AI hallucinations." What are they, why do they happen, and how can I spot when you might be making something up?', 'Learn to identify and handle AI inaccuracies', 12, '{ "Ask for real examples of common hallucination scenarios", "Request strategies for fact-checking AI responses", "Try to get the AI to hallucinate on purpose to see what happens" }', '[{"title": "AI Hallucinations Explained", "url": "https://www.ibm.com/think/topics/ai-hallucinations"}]', NOW()),
('prompt-2-2', 'course-1', 'Module 2: Problem - Common AI Challenges', 5, 'Ask AI to tell you who won the Nobel Prize in Literature in 2024. Then verify this answer using a search engine. Come back and tell the AI whether it was correct.', 'Practice fact-checking AI responses with external sources', 15, '{ "Notice if the AI hedges its answer or expresses uncertainty", "Pay attention to how recent events affect AI accuracy", "Discuss what you learned about verifying AI information" }', '[]', NOW()),
('prompt-2-3', 'course-1', 'Module 2: Problem - Common AI Challenges', 6, 'I notice AI sometimes gives different answers to the same question. Explain why this happens and whether this is a feature or a bug.', 'Understand AI response variability and temperature', 10, '{ "Ask about what \"temperature\" means in AI settings", "Explore when variability is helpful vs. problematic", "Try asking the same question twice to see the difference" }', '[]', NOW()),
('prompt-3-1', 'course-1', 'Module 3: Plan - Effective Communication', 7, 'I need to write a professional email to my manager asking for time off next month. Can you help me draft this email?', 'Learn basic prompt writing for practical tasks', 10, '{ "Notice what information you need to provide for a good result", "Try asking for multiple versions with different tones", "Request revisions if the first draft isn''t quite right" }', '[]', NOW()),
('prompt-3-2', 'course-1', 'Module 3: Plan - Effective Communication', 8, 'Take the email you just helped me write and make it more casual and friendly. Then make another version that''s extremely formal.', 'Learn to request specific tone modifications', 8, '{ "Compare the three versions to see how tone changes language", "Identify specific words/phrases that create different tones", "Practice requesting specific style changes" }', '[]', NOW()),
('prompt-3-3', 'course-1', 'Module 3: Plan - Effective Communication', 9, 'Teach me the CLEAR framework for writing good prompts: Context, Length, Examples, Audience, and Result. Give me an example of a bad prompt vs. a good prompt using this framework.', 'Learn a structured approach to writing effective prompts', 15, '{ "Write down the framework for future reference", "Practice rewriting your own past prompts using CLEAR", "Ask for more examples in different domains" }', '[]', NOW()),
('prompt-4-1', 'course-1', 'Module 4: Pivot - Iteration & Refinement', 10, 'I want to explain blockchain technology to my grandmother. Start with a simple explanation and I''ll tell you what parts need more clarity.', 'Practice iterative refinement through back-and-forth dialogue', 12, '{ "Don''t accept the first explanation if it''s not perfect", "Point out specific parts that are too complex", "Keep refining until you''re satisfied with the explanation" }', '[]', NOW()),
('prompt-4-2', 'course-1', 'Module 4: Pivot - Iteration & Refinement', 11, 'What are some phrases I can use when AI doesn''t give me what I want? Give me a toolkit of "follow-up phrases" to redirect the conversation.', 'Build a vocabulary for redirecting AI conversations', 10, '{ "Save these phrases somewhere for future use", "Try each phrase out in this conversation", "Identify which phrases work best for different situations" }', '[]', NOW()),
('prompt-4-3', 'course-1', 'Module 4: Pivot - Iteration & Refinement', 12, 'I asked you for a recipe earlier and got something I didn''t like. Help me understand how to give better feedback to get better results. What should I say instead of "no, try again"?', 'Learn effective feedback techniques for AI interactions', 10, '{ "Practice specific feedback vs. vague feedback", "Try actually using the techniques in this conversation", "Notice how specific feedback generates better revisions" }', '[]', NOW()),
('prompt-5-1', 'course-1', 'Module 5: Payoff - Putting It Together', 13, 'Let''s complete a real project together. I want to create a 1-week study plan for learning [topic of your choice]. Walk me through how to collaborate with you effectively to make this plan.', 'Apply learned skills to a complete project', 20, '{ "Use the CLEAR framework from earlier", "Practice iterative refinement throughout", "Apply fact-checking for any claims about learning methods" }', '[]', NOW()),
('prompt-5-2', 'course-1', 'Module 5: Payoff - Putting It Together', 14, 'Review our study plan. Act as a critical reviewer and point out any weaknesses or unrealistic assumptions. Then help me fix them.', 'Learn to use AI for self-review and improvement', 15, '{ "Embrace the criticism - it makes results better", "Ask the AI to be even more critical if feedback is too gentle", "Notice how role-playing affects AI behavior" }', '[]', NOW()),
('prompt-5-3', 'course-1', 'Module 5: Payoff - Putting It Together', 15, 'Summarize everything I''ve learned in this course about working with AI. Create a personal "AI User Guide" that I can reference in the future.', 'Synthesize learning into a reusable reference document', 15, '{ "Ask for it in your preferred format (bullets, numbered list, etc.)", "Request specific examples for each tip", "Save this document for future reference" }', '[]', NOW())
ON CONFLICT (id) DO UPDATE SET
  course_id = EXCLUDED.course_id,
  module_name = EXCLUDED.module_name,
  prompt_order = EXCLUDED.prompt_order,
  prompt_text = EXCLUDED.prompt_text,
  learning_goal = EXCLUDED.learning_goal,
  estimated_time_minutes = EXCLUDED.estimated_time_minutes,
  tips = EXCLUDED.tips,
  resources = EXCLUDED.resources;
